server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketmaster_db?currentSchema=event}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: true
    default-schema: event
    schemas: event
    table: flyway_history_event
    locations: classpath:db/migration

management:
  endpoints.web.exposure.include: health,info

elastic:
  base-url: ${ELASTIC_HOST:http://elasticsearch:9200}
outbox:
  relay:
    interval: 1000