server:
  port: 8080

security:
  jwt:
    secret: ${JWT_SECRET:change-me}

spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  cloud:
    gateway:
      routes:
        - id: events
          uri: ${EVENT_SERVICE_URI:http://event-service:8081}
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                rate-limiter: "#{@userRateLimiter}"

        - id: reservations
          uri: ${BOOKING_SERVICE_URI:http://booking-service:8082}
          predicates:
            - Path=/api/reservations/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                rate-limiter: "#{@userRateLimiter}"

        - id: search
          uri: ${SEARCH_SERVICE_URI:http://search-service:8083}
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                rate-limiter: "#{@userRateLimiter}"
